package uz.gita.a4picture1word.domain.repository.impl

import uz.gita.a4picture1word.R
import uz.gita.a4picture1word.data.model.GameData
import uz.gita.a4picture1word.domain.repository.AppRepository
import javax.inject.Inject

class AppRepositoryImpl @Inject constructor() : AppRepository {
    private val list = ArrayList<GameData>()

    init {
        loadData()
    }

    private fun loadData() {
        list.add(
            GameData(
                R.drawable.yi1er1er1,
                R.drawable.yi1er1er2,
                R.drawable.yi1er1er3,
                R.drawable.yi1er1er4,
                "CUP",
                "CUPIGADPHXDF"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er2er1,
                R.drawable.yi1er2er2,
                R.drawable.yi1er2er3,
                R.drawable.yi1er2er4,
                "FLY",
                "FLYTWHTXFSGR"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er3er1,
                R.drawable.yi1er3er2,
                R.drawable.yi1er3er3,
                R.drawable.yi1er3er4,
                "BALLOON",
                "BALLOONTMSIW"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er4er1,
                R.drawable.yi1er4er2,
                R.drawable.yi1er4er3,
                R.drawable.yi1er4er4,
                "SUN",
                "SUNDFTWSBMHW"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er5er1,
                R.drawable.yi1er5er2,
                R.drawable.yi1er5er3,
                R.drawable.yi1er5er4,
                "TRAIN",
                "TRAINMXSGENW"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er6er1,
                R.drawable.yi1er6er2,
                R.drawable.yi1er6er3,
                R.drawable.yi1er6er4,
                "RING",
                "RINGYMPFBGLT"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er7er1,
                R.drawable.yi1er7er2,
                R.drawable.yi1er7er3,
                R.drawable.yi1er7er4,
                "COFFEE",
                "COFFEEIYGFHS"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er8er1,
                R.drawable.yi1er8er2,
                R.drawable.yi1er8er3,
                R.drawable.yi1er8er4,
                "YELLOW",
                "YELLOWEIRVCD"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er9er1,
                R.drawable.yi1er9er2,
                R.drawable.yi1er9er3,
                R.drawable.yi1er9er4,
                "RIVER",
                "RIVERKRWGFFR"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er10er1,
                R.drawable.yi1er10er2,
                R.drawable.yi1er10er3,
                R.drawable.yi1er10er4,
                "PIZZA",
                "PIZZAIKUCRUO"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er11er1,
                R.drawable.yi1er11er2,
                R.drawable.yi1er11er3,
                R.drawable.yi1er11er4,
                "JUMP",
                "JUMPRATQMSOY"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er12er1,
                R.drawable.yi1er12er2,
                R.drawable.yi1er12er3,
                R.drawable.yi1er12er4,
                "GREEN",
                "GREENJAWEGLC"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er13er1,
                R.drawable.yi1er13er2,
                R.drawable.yi1er13er3,
                R.drawable.yi1er13er4,
                "HOUSE",
                "HOUSEBQNAMOT"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er14er1,
                R.drawable.yi1er14er2,
                R.drawable.yi1er14er3,
                R.drawable.yi1er14er4,
                "BATTERY",
                "BATTERYIOFCK"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er15er1,
                R.drawable.yi1er15er2,
                R.drawable.yi1er15er3,
                R.drawable.yi1er15er4,
                "SWIM",
                "SWIMICTPWGLV"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er16er1,
                R.drawable.yi1er16er2,
                R.drawable.yi1er16er3,
                R.drawable.yi1er16er4,
                "COLD",
                "COLDAMHISPVE"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er17er1,
                R.drawable.yi1er17er2,
                R.drawable.yi1er17er3,
                R.drawable.yi1er17er4,
                "BRAIN",
                "BRAINMDABBNX"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er18er1,
                R.drawable.yi1er18er2,
                R.drawable.yi1er18er3,
                R.drawable.yi1er18er4,
                "CLIP",
                "CLIPVNFUQEYM"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er19er1,
                R.drawable.yi1er19er2,
                R.drawable.yi1er19er3,
                R.drawable.yi1er19er4,
                "HAND",
                "HANDEYXERBBY"
            )
        )

        list.add(
            GameData(
                R.drawable.yi1er20er1,
                R.drawable.yi1er20er2,
                R.drawable.yi1er20er3,
                R.drawable.yi1er20er4,
                "DOG",
                "DOGQJBHKYOJB"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er21er1,
                R.drawable.yi1er21er2,
                R.drawable.yi1er21er3,
                R.drawable.yi1er21er4,
                "CHILDREN",
                "CHILDRENTCEB"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er22er1,
                R.drawable.yi1er22er2,
                R.drawable.yi1er22er3,
                R.drawable.yi1er22er4,
                "MOUNTAIN",
                "MOUNTAINJIVR"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er23er1,
                R.drawable.yi1er23er2,
                R.drawable.yi1er23er3,
                R.drawable.yi1er23er4,
                "CHAIR",
                "CHAIREIYHNRQ"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er24er1,
                R.drawable.yi1er24er2,
                R.drawable.yi1er24er3,
                R.drawable.yi1er24er4,
                "BED",
                "BEDVELXNNQED"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er25er1,
                R.drawable.yi1er25er2,
                R.drawable.yi1er25er3,
                R.drawable.yi1er25er3,
                "CAT",
                "CATRIEYHTCFC"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er26er1,
                R.drawable.yi1er26er2,
                R.drawable.yi1er26er3,
                R.drawable.yi1er26er4,
                "FRUIT",
                "FRUITTBBKLYS"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er27er1,
                R.drawable.yi1er27er2,
                R.drawable.yi1er27er3,
                R.drawable.yi1er27er4,
                "MATCH",
                "MATCHHLBNOSK"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er28er1,
                R.drawable.yi1er28er2,
                R.drawable.yi1er28er3,
                R.drawable.yi1er28er4,
                "BREAK",
                "BREAKPEVTMGN"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er29er1,
                R.drawable.yi1er29er2,
                R.drawable.yi1er29er3,
                R.drawable.yi1er29er4,
                "ICE",
                "ICEXIBLEFCGH"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er30er1,
                R.drawable.yi1er30er2,
                R.drawable.yi1er30er3,
                R.drawable.yi1er30er4,
                "AIRPLANE",
                "AIRPLANEMMPY"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er31er1,
                R.drawable.yi1er31er2,
                R.drawable.yi1er31er3,
                R.drawable.yi1er31er4,
                "CYCLE",
                "CYCLERDWYRXT"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er32er1,
                R.drawable.yi1er32er2,
                R.drawable.yi1er32er3,
                R.drawable.yi1er32er4,
                "POTATO",
                "POTATOAUYQMT"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er33er1,
                R.drawable.yi1er33er2,
                R.drawable.yi1er33er3,
                R.drawable.yi1er33er4,
                "RED",
                "REDFFVSRRFAV"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er34er1,
                R.drawable.yi1er34er2,
                R.drawable.yi1er34er3,
                R.drawable.yi1er34er4,
                "MEETING",
                "MEETINGLEXLR"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er35er1,
                R.drawable.yi1er35er2,
                R.drawable.yi1er35er3,
                R.drawable.yi1er35er4,
                "MASK",
                "MASKOYIBKIHC"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er36er1,
                R.drawable.yi1er36er2,
                R.drawable.yi1er36er3,
                R.drawable.yi1er36er4,
                "STAR",
                "STARGTRAFPFC"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er37er1,
                R.drawable.yi1er37er2,
                R.drawable.yi1er37er3,
                R.drawable.yi1er37er4,
                "BOX",
                "BOXKQJXXIBDS"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er38er1,
                R.drawable.yi1er38er2,
                R.drawable.yi1er38er3,
                R.drawable.yi1er38er4,
                "BALL",
                "BALLINGYEKSL"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er39er1,
                R.drawable.yi1er39er2,
                R.drawable.yi1er39er3,
                R.drawable.yi1er39er4,
                "KISS",
                "KISSLICTLIAT"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er40er1,
                R.drawable.yi1er40er2,
                R.drawable.yi1er40er3,
                R.drawable.yi1er40er4,
                "BAG",
                "BAGGKQMJTFCS"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er41er1,
                R.drawable.yi1er41er2,
                R.drawable.yi1er41er3,
                R.drawable.yi1er41er4,
                "MAGAZINE",
                "MAGAZINEFGSU"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er42er1,
                R.drawable.yi1er42er2,
                R.drawable.yi1er42er3,
                R.drawable.yi1er42er4,
                "CREAM",
                "CREAMQMQCQLO"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er43er1,
                R.drawable.yi1er43er2,
                R.drawable.yi1er43er3,
                R.drawable.yi1er43er4,
                "CREAM",
                "CREAMQMQCQLO"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er44er1,
                R.drawable.yi1er44er2,
                R.drawable.yi1er44er3,
                R.drawable.yi1er44er4,
                "GLASSES",
                "GLASSESFROPQ"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er45er1,
                R.drawable.yi1er45er2,
                R.drawable.yi1er45er3,
                R.drawable.yi1er45er4,
                "MAP",
                "MAPATIONFVYS"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er45er1,
                R.drawable.yi1er45er2,
                R.drawable.yi1er45er3,
                R.drawable.yi1er45er4,
                "SLEEP",
                "SLEEPONTDGSQ"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er46er1,
                R.drawable.yi1er46er2,
                R.drawable.yi1er46er3,
                R.drawable.yi1er46er4,
                "HUG",
                "HUGRACEQKJVV"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er47er1,
                R.drawable.yi1er47er2,
                R.drawable.yi1er47er3,
                R.drawable.yi1er47er4,
                "BOWLING",
                "BOWLINGEKPTK"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er48er1,
                R.drawable.yi1er48er2,
                R.drawable.yi1er48er3,
                R.drawable.yi1er48er4,
                "CAMERA",
                "CAMERAEHNMGN"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er49er1,
                R.drawable.yi1er49er2,
                R.drawable.yi1er49er3,
                R.drawable.yi1er49er4,
                "FLOWER",
                "FLOWERNTBAAQ"
            )
        )
        list.add(
            GameData(
                R.drawable.yi1er50er1,
                R.drawable.yi1er50er2,
                R.drawable.yi1er50er3,
                R.drawable.yi1er50er4,
                "OWL",
                "OWLDMILLNFPQ"
            )
        )

    }

    override fun getData(pos: Int): GameData {
        return list[pos]
    }

    override fun getSize(): Int {
        return list.size
    }
}